version: '2'
services:
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zoo-docker:2181
    volumes:
      - $PWD/data:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
      - docker_net
  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: zoo-docker:2181
    volumes:
      - $PWD/data:/kafka
    networks:
      - default
      - docker_net
networks:
  docker_net:
    external: true
